### ISSUE TITLE
iesi-setenv.sh cannot be run from outside the bin/ directory

### ISSUE THREAD

**Issue by peterbillen** [metadew/iesi#112]
**Describe the bug**
iesi-setenv.sh cannot be run from outside the bin/ directory

**To Reproduce**
1. Go to $iesi-home
2. Run bin/iesi-metadata.sh -create -type general
3. See error message: iesi-setenv.sh: line 6: cd: bin: No such file or directory

**Expected behavior**
Correct behaviour

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
Linux OS

**Comment by BerrevoetsRobbe** [comment]
iesi-setenv will be obsolete as of next release (v0.4.0)
