### ISSUE TITLE
Rest server - add request for script results based on run id

### ISSUE THREAD

**Issue by peterbillen** [metadew/iesi#132]
**Is your feature request related to a problem? Please describe.**
I would like to retrieve the script results from the rest server via the run id of the execution.

**Describe the solution you'd like**
A new request in the rest server

**Describe alternatives you've considered**
NA

**Additional context**
NA

**ID**
0718c6b

**Comment by Levizar** [comment]
duplicated and solved in issue https://github.com/metadew/iesi/pull/156
