### ISSUE TITLE
resolveConceptLookup more tolerant to spaces

### ISSUE THREAD

**Issue by Sroose** [metadew/iesi#24]
Improvement request:
`{{=connection(crm_postgres, host)}}` does not work because of the space after the comma (second argument is considered to be " host"). Maybe we can trim the parts after splitting.

**Comment by metadew** [comment]
merged fix

**Comment by Sroose** [comment]
The fix for this bug was not part of PR 26

**Comment by Sroose** [comment]
The fix for this bug was not part of PR 26
