### ISSUE TITLE
resolveConceptLookup does not handle multiple occurences correctly

### ISSUE THREAD

**Issue by Sroose** [metadew/iesi#25]
a command involving more than 1 subsitution variable will fail:
`somecommand -host={{=connection(target_postgres,host)}} -port={{=connection(target_postgres,port)}}`
(nullpointer exception)

Reason: the parsing and locating of the ending braces is not done correctly

**Comment by Sroose** [comment]
Created PR #26

**Comment by metadew** [comment]
merged fix
