### ISSUE TITLE
Script Execution - No automatic termination

### ISSUE THREAD

**Issue by NairiBonte** [metadew/iesi#98]
**Describe the bug**
When executing a script through cmd-line, the script/job is not automatically terminated when the script is finished. A manual intervention is needed to terminate the batch job for every execution. 

**To Reproduce**
1. Launch your script through cmd prompt
2. Fully execute the script
3. Manual action needed to terminate batch job

**Expected behavior**
1. Launch your script through cmd prompt
2. Fully execute the script
3. Job automatically terminated once the script run is finished

**Additional Information**
- Local execution
- Termination only possible with Ctrl + C

![Termination_issue](https://user-images.githubusercontent.com/45843206/72335689-b023a180-36bf-11ea-9adb-589c9b2f109c.jpg)

**Comment by BerrevoetsRobbe** [comment]
Non reproducable
